name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'github.com/AleksanderMoosieno'
inputs:
  LABEL:
    description: 'Label description'
    required: true
    default: 'default-value'


inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  REPOSITORY:
    description: 'The repository where the action will be executed.'
    required: true
  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  SCRIPT_PATH:
    description: 'The path to the script that interacts with ChatGPT and generates code.'
    required: false
    default: scripts/script.sh
  LABEL:
    description: 'Allows users to customize the label that triggers the action.'
    required: true

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'

runs:
  using: 'composite'

  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
            
    - name: Make Script Executable
      run: chmod +x ./scripts/script.sh
        
    - name: Creating yml
      run: ./scripts/script.sh ${GITHUB_TOKEN}, ${REPOSITORY}, ${ISSUE_NUMBER}, ${CHAT_GPT_API} # > output.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
      - name: autocoder-artifact
        path: |
            *

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: ./autocoder-artifact
     
      - name: List Files Recursively
        run: |
          echo "Listing all files in autocoder-artifact directory:"
          ls -R autocoder-artifact/

      - name: Copy Generated Code to a dedicated folder
        run: |
          mkdir -p autocoder-generated
          cp -R autocoder-artifact/* autocoder-generated/

      - name: Debug - List Copied Files in autocoder-generated
        run: ls -R autocoder-generated

      - name: Force a change for PR detection
        run: |
          echo "// Force change: $(date)" > autocoder-generated/force_change.txt

      - name: Configure Git
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"

      - name: Debug Git Status Before Commit
        run: |
          git status

      - name: Commit Generated Code
        run: |
          git config --local user.name "autocoder-bot"
          git config --local user.email "actions@github.com"
          git add ./autocoder-artifact
          git commit -m "Add generated code from ChatGPT"
      
      - name: Debug - Final Git Status
        run: git status
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          labels: "autocoder-bot"
          author: autocoder-bot <actions@github.com>
          title: "PR to issue #${{ env.ISSUE_NUMBER }}"
          branch: autocoder-branch-${{ env.ISSUE_NUMBER }}
