name: Access Issue Information
on:
  issues:
    types: [opened, reopened, labeled]
permissions:
  contents: write
  issues: write
  pull-requests: write
env: 
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  REPOSITORY: ${{ github.repository }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  CHAT_GPT_API: ${{ secrets.API }}
  ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
jobs:
  asking_chat_bot:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
            
      - name: Make Script Executable
        run: chmod +x ./scripts/script.sh
        
      - name: Creating yml
        run: ./scripts/script.sh ${GITHUB_TOKEN}, ${REPOSITORY}, ${ISSUE_NUMBER}, ${CHAT_GPT_API} # > output.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: |
            *

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: ./autocoder-artifact
     
      - name: List Files Recursively
        run: |
          echo "Listing all files in autocoder-artifact directory:"
          ls -R autocoder-artifact/

      - name: Copy Generated Code to a dedicated folder
        run: |
          mkdir -p autocoder-generated
          cp -R autocoder-artifact/* autocoder-generated/

      - name: Debug - List Copied Files in autocoder-generated
        run: ls -R autocoder-generated

      - name: Force a change for PR detection
        run: |
          echo "// Force change: $(date)" > autocoder-generated/force_change.txt

      - name: Configure Git
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"

      - name: Debug Git Status Before Commit
        run: |
          git status

      - name: Commit Generated Code
        run: |
          # Create or update the branch
          git checkout -B autocoder-branch-${{ github.event.issue.number }}
          # Stage everything in the dedicated folder
          git add autocoder-generated
          git status
          # Commit, explicitly setting the author
          git commit \
            --author="autocoder-bot <actions@github.com>" \
            -m "Autocoder generated code for issue #${{ github.event.issue.number }}"
          # Force-push to overwrite any existing branch
          git push -f origin autocoder-branch-${{ github.event.issue.number }}
      
      - name: Debug - Final Git Status
        run: git status
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          labels: "autocoder-bot"
          author: autocoder-bot <actions@github.com>
          title: "PR to issue #${{ inputs.ISSUE_NUMBER }}"
          branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
