name: Access Issue Information
on:
  issues:
    types:
      - opened
      - reopened
jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Print Issue Information     
      env:
        GITHUB_TOKEN: ${{ env.TOKEN }}
        REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
      run: |
        env
        printenv
