name: Access Issue Information
on:
  issues:
    types: [opened, reopened, labeled]
permissions:
  contents: read
  issues: write
  pull-requests: write
env: 
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  REPOSITORY: ${{ github.repository }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  CHAT_GPT_API: ${{ secrets.API }}
  ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
jobs:
  asking_chat_bot:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Git user
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"
      
      - name: Commit generated files
        run: |
          git add .
          git commit -m "AutoCode: Generated files for issue ${{ github.event.issue.labels.*.name }}"
      
      - name: Make Script Executable
        run: chmod +x ./scripts/script.sh
        
      - name: Creating yml
        run: ./scripts/script.sh ${GITHUB_TOKEN}, ${REPOSITORY}, ${ISSUE_NUMBER}, ${CHAT_GPT_API} # > output.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: |
            *
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: autocoder-branch-${{ github.event.issue.labels.*.name }}
          title: "AutoCode PR for Issue ${{ github.event.issue.labels.*.name }}"
          base: main
          labels: autocoder-bot
          commit-message: "AutoCode: Generated files for issue ${{ github.event.issue.labels.*.name }}"
          body: |
            Automatically generated pull request for issue ${{ github.event.issue.labels.*.name }}
            
            Generated by autocoder-bot 

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: ./autocoder-artifact
     
      - name: List Files Recursively
        run: |
          echo "Listing all files in autocoder-artifact directory:"
          ls -R autocoder-artifact/
