name: Access Issue Information

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Print Issue Information
        env:
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
          # Правильное обращение к секретам
          OPENAI_API_KEY: ${{ secrets.TK }}
        run: |
          echo "=== Environment variables ==="
          echo "REPOSITORY: $REPOSITORY"
          echo "ISSUE_NUMBER: $ISSUE_NUMBER"
          echo "ISSUE_LABELS: $ISSUE_LABELS"
          echo "OPENAI_API_KEY (length): ${#OPENAI_API_KEY}"  # Покажет длину строки (0 если пусто)
          
          touch .env
          echo "GITHUB_REPO=$REPOSITORY" >> .env
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> .env
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
          
          echo "=== .env file content ==="
          cat .env
