name: AutoCoder Workflow

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate_code:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot') # Check for the label at the job level
