name: Autocoder Bot Processing

on:
  issues:
    types: [labeled]

jobs:
  process-autocoder:
    runs-on: ubuntu-latest
    # Проверяем, что issue имеет метку autocoder-bot
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./scripts/autocoder.sh

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          REPO_NAME: ${{ github.repository }}
        run: |
          ./scripts/autocoder.sh "$ISSUE_TITLE" "$ISSUE_BODY" "$REPO_NAME"
          echo "Generated files:"
          ls -R ./autocoder-artifact

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: autocoder-artifact
          path: ./autocoder-artifact
          retention-days: 1

      - name: Display Generated Code
        run: |
          echo "Generated files structure:"
          ls -R ./autocoder-artifact
          echo ""
          echo "File contents:"
          find ./autocoder-artifact -type f -exec sh -c 'echo "\n=== {} ==="; cat {}' \;
