name: Autocoder Bot Processor

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    # Only run if the issue has the autocoder-bot label
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'autocoder-bot') ||
      (github.event.action != 'labeled' && contains(github.event.issue.labels.*.name, 'autocoder-bot'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify label
        run: |
          echo "Event action: ${{ github.event.action }}"
          echo "Issue labels: ${{ toJSON(github.event.issue.labels) }}"
          echo "Label added (if labeled event): ${{ github.event.label.name }}"

      - name: Prepare environment
        run: |
          mkdir -p ./autocoder-artifact
          chmod +x ./scripts/autocoder.sh

      - name: Execute autocoder script
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_LABELS: ${{ toJSON(github.event.issue.labels) }}
          REPO_NAME: ${{ github.repository }}
          EVENT_TYPE: ${{ github.event.action }}
        run: |
          ./scripts/autocoder.sh "$ISSUE_TITLE" "$ISSUE_BODY" "$REPO_NAME" "$ISSUE_LABELS" "$EVENT_TYPE"
          echo "Generated files:"
          ls -R ./autocoder-artifact

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: autocoder-artifact
          path: ./autocoder-artifact/
          retention-days: 1

      - name: Display results
        run: |
          echo "=== Generated Files Structure ==="
          find ./autocoder-artifact -type d -exec echo "Directory: {}" \; -exec ls -la {} \;
          echo "\n=== File Contents ==="
          find ./autocoder-artifact -type f -exec echo "\n=== {} ===" \; -exec cat {} \;
